### PR TITLE
Amend scrapy open_in_browser tool.

### PR DESCRIPTION
**Pull request by bulatbulat48**
Fixes https://github.com/scrapinghub/scrapy-poet/issues/91

The error:
```
open_in_browser(po.response)
Traceback (most recent call last):
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydevd_bundle/pydevd_exec2.py", line 3, in Exec
    exec(exp, global_vars, local_vars)
  File "<input>", line 1, in <module>
  File "/Users/bulat/PycharmProjects/zyteprojects/envs/web-poet/lib/python3.10/site-packages/scrapy/utils/response.py", line 101, in open_in_browser
    raise TypeError("Unsupported response type: " f"{response.__class__.__name__}")
TypeError: Unsupported response type: HttpResponse
```

### CODE REVIEW

**Comment by Gallaecio** [comment]
Python 3.7 is end of life, so rather than looking for a compatible approach, feel free to modify the code base (tox.ini, setup.py, README) to drop 3.7 support.

**Comment by bulatbulat48** [comment]
@Gallaecio fixed in https://github.com/scrapinghub/scrapy-poet/pull/155

**Comment by Gallaecio** [comment]
Now that tests pass, I think the only missing piece is docs. I am not sure where to mention it, though. Maybe a new, short section in https://scrapy-poet.readthedocs.io/en/stable/intro/pitfalls.html , just so that we can link to it when people run into the issue?

**Comment by bulatbulat48** [comment]
> Now that tests pass, I think the only missing piece is docs. I am not sure where to mention it, though. Maybe a new, short section in https://scrapy-poet.readthedocs.io/en/stable/intro/pitfalls.html , just so that we can link to it when people run into the issue?

@Gallaecio added help section. But tests fail again :)

**Pull request merged**
